#### Generalizing it even more, how does embedding the characters and position as multi-dimensional arrays/tensors, still retain the information of these characters and positions? in essence their "characteristics

Embedding characters and their positions as multi-dimensional arrays (tensors) might initially seem like it could obscure their individual characteristics, but this technique is foundational to the success of neural networks in natural language processing (NLP) and other tasks. Let's break down why this works and how it retains the necessary information:


Embedding Process: A Quick Recap
1. Token Embedding:
Each character (or token) is mapped to a high-dimensional vector.
These vectors are learned during training, capturing semantic properties of characters or words.

3. Positional Embedding:
Each position in a sequence is also mapped to a high-dimensional vector.
These vectors encode positional information, ensuring the model can differentiate between the same token in different positions.

#### How Information is Retained
1. Semantic Information from Token Embeddings
- Learning Representations: During training, the model learns to adjust the embeddings such that characters with similar roles in context have similar vectors. For example, 'a' and 'e' might have embeddings that are closer in vector space than 'a' and 'z'.
- Dimensionality: High-dimensional vectors can capture a wide range of characteristics. Each dimension of the vector can represent a different aspect of the character's role in language (e.g., phonetic features, position in words, syntactic roles).


2. Positional Information from Positional Embeddings
- Relative Positioning: Positional embeddings ensure that the model knows the position of each token within a sequence. This allows the model to understand context in a way that respects the order of tokens.
- Distinct Embeddings: Each position gets a unique vector, which when added to the token embeddings, creates a combined vector that is unique to both the character and its position.


3. Combination of Token and Positional Embeddings
- Element-wise Addition: By adding positional embeddings to token embeddings, the resulting vectors carry both the semantic meaning of the token and its positional context.
- Learning Patterns: The neural network learns to interpret these combined vectors. For example, 'e' at the beginning of a word might be interpreted differently from 'e' at the end of a word because the positional embeddings modify the token embeddings in a meaningful way.

#### Why This Retains Characteristics
- High-Dimensional Space: The high dimensionality allows for rich representations where different dimensions can capture different aspects of the token and its context.

- Contextual Relationships: The model learns contextual relationships. For example, 'h' followed by 'e' followed by 'l' might learn to represent the sequence 'hel' differently than 'elh' even though the token embeddings for 'h', 'e', and 'l' are the same in both sequences.

- Differentiability: Neural networks, especially deep ones, are powerful function approximators. The embeddings allow the network to differentiate and learn complex patterns and relationships in the data.

In [1]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [3]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [4]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [5]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [6]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [7]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [8]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [10]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

# So we have 32 examples in each batch
# 1st : [24] -> 43
# 2nd : [24, 43] -> 58
# 3rd : [24, 43, 58] -> 5
# 4th : ...

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [11]:
print(xb) # our input to the transformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    # Embedding table is the one we pluck out rows from

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        # Batch = 4, Time = 8, Channels(vocab Size) = 65

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape # Re-shape our logits to fit pytorch's expectations
            logits = logits.view(B*T, C) # Change to 2D
            targets = targets.view(B*T) # Change to fit new logits 2D dimensions, (can also put -1)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C) #The logit probs of 65 characters of 4 sequences at Time = 8th
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence (Across dimension T / dimension 1)
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)
#torch.zeros((1, 1) zero itos is the new line character, this will kick off the generation
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist())) # [0]  to index into the row of integers


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [13]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [14]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5727508068084717


In [15]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


Iyoteng h hasbe pave pirance
Rie hicomyonthar's
Plinseard ith henoure wounonthioneir thondy, y heltieiengerofo'dsssit ey
KIN d pe wither vouprrouthercc.
hathe; d!
My hind tt hinig t ouchos tes; st yo hind wotte grotonear 'so it t jod weancotha:
h hay.JUCle n prids, r loncave w hollular s O:
HIs; ht anjx?

DUThinqunt.

LaZAnde.
athave l.
KEONH:
ARThanco be y,-hedarwnoddy scace, tridesar, wnl'shenous s ls, theresseys
PlorseelapinghiybHen yof GLUCEN t l-t E:
I hisgothers je are!-e!
QLYotouciullle'z


## The mathematical trick in self-attention

In [16]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"

torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [17]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [18]:
# We want x[b,t] = mean_{i<=t} x[b,i] # finding the average for all i <= t, nth > t since thats in the future
xbow = torch.zeros((B,T,C)) # xbow = x bag of words
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # xprev has shape (t,C), contains t rows of C
        xbow[b,t] = torch.mean(xprev, 0)

In [19]:
# x[0], xbow[0]

In [20]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T)) # wei = weights
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C) 
# For each Batch element, there is a [T, T] @ [T, C]
# wei is originally [T, T] but pytorch sorta like broadcasts it B times
torch.allclose(xbow, xbow2)

False

In [21]:
#xbow[0], xbow2[0]
#hmm shud be true

In [22]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf')) # all elements that == 0 becomes -infinity
wei = F.softmax(wei, dim=-1) # exponentiate and then normalize
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

False

What we were doing was, simply summing the current values of embeds and previous values of embeds and finding the average value across each dimension. This averaged value of embeds describes the current group of chars 

### HOWEVER

We do not want it to be a normal average, as some characters previously should hold more prevalence. K Q V fixes this

## What is wei exactly?
Contains the affinities


Each element would represent the affinity between tokens. If set to -inf it means they cannot "talk" to each other (Future cannot communicate to past)


THIS IS SELF-ATTENTION


Characters that are either consonants or vowels can talk to each other, in past positions, based on their affinities. Before self-attention, we couldnt fully capture this relationship?

Every single node/token at each position will emit 2 vectors. It will emit a query and a key. 

- Query : What I am looking for
- Key : What do I contain
- To calculate the affinities : My query dot products with all the keys of the other tokens and that dot product now becomes wei


### Calculating wei :
If a key and a query are "aligned" they will interact with a very high amount and then I will get to learn more about that specific token compared to other tokens. 


In [23]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16) # Each element at Batch of each Time now has Key and a Query (they are vectors of 16 elements)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)  # Communication portion!!!
# ( -2, -1) is to transpose the last 2 dimensions, B sorta just acts like a jar holding the [T, 16] and [16, T] arrays

tril = torch.tril(torch.ones(T, T)) # lower triangular
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf')) # .masked_fill invalidates future characters using the mask tril
wei = F.softmax(wei, dim=-1)

v = value(x) # we dont want to use raw x, v contains like 16 params that "Describes" x in a sense?
out = wei @ v  # (B, T, T) @ (B, T, 16) ---> (B, T, 16)
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

### Trying to describe what we're doing

In the end, you end up with a tensor of 4 batches, time = 8, where in each time contains the head_sizes for 1 character, but instead of only describing this 1 character like a vector character embed, it now describes the character within the premises of PREVIOUS characters as well. 

so the "e" in "broke"(b+r+o+k+e & positional vectors @ wei]) is vastly different from the "e" in "spread" (s+p+r+e & positional vectors @ wei) , 

however, the "a" in air" and "apple" would have the same "vector description" since the "a" cant talk to the future

In [24]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

## Notes:

- Attention is a communication mechanism. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with tril, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides wei by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [25]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5 # divide by head space so that variance is preserved at 1

In [26]:
k.var()

tensor(1.0449)

In [27]:
q.var()

tensor(1.0700)

In [28]:
wei.var()

tensor(1.0918)

#### Must
divide wei by squareroot of dimensionality of head_size before softmax, if not variance will be on the order of dimensionality of head_size, leading to huge differences hence one hot vectors.

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [30]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot
# hence, need to control the scaling

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

### Multi-headed self attention blocks
init : self.sa_heads = MultiHeadAttention(4, n_embed//4)
Split into 4 channels of 8 dimensional S.A. which then concatenated back into 32 (our original n_embed)[ Head size is always = n_embed / 4 ]. Similar to grouped convolutions. Helps to have multiple communication channels because these tokens have alot to talk about. They want to find consonants, vowels, consonants in specific positions etc..

### Feed Forward Network

Just a simple multi-layer perceptron (contains Linear followed by ReLu). Jumping from multi-headed S.A. to calculating logits is too fast. So the tokens looked at each other but didnt really have enough time to think on what they had found from the other tokens. 
- note that the interdimensionality of the Feed Forward Layer should be 4 * fan_in, but output still returns fan_in
- ffn placed after sa layer

### Block
Intersperses communication and computation.
- Communication done by multi-headed S.A.
- Computation done by Feed Forward
- on all the tokens independently?


Block architecture : 

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


### Residual Connections

Gradient superhighway. Easier Training: Deeper networks often suffer from the vanishing gradient problem, where gradients become very small as they propagate back through many layers, making training difficult. Residual connections mitigate this issue by providing shortcut paths for gradients.


Is a separate pathway that allows for unempeded path from our output back to inputs during backpropagation. In a sense, the blocks(contains the actual transformations) are first offline during initialization but slowly come online during optimization.

- helps make model optimizable
- after forking off from main branch, it is added back through addition
- have to add a projection layer into SA and FFN as they act like the connectors back into residual pathway.

### LayerNorm

In [31]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [32]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [33]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

BatchNorm used to normalize the activations of the SAME neuron across different examples.

    
LayerNorm normalizes the activations of different neurons across the SAME example


- no longer a need for running buffers (running variance/mean since its all done within one example)
- placed before transformations(sa & ffn), and also right BEFORE final layer where we get predictions(size vocab size)

### Dropout

- placed before merging back into residual layer
- prevents overfitting
- randomly drops some neurons to weight 0 during both forward and backward pass
- smth like training subnets first and then during validation we put everything tgt

  Used at :
  - wei before wei @ v
  - concatenated features of multi sa (turns out proj layer was not last layer)
  - ffn last layer (turns out proj layer was not last layer)

In [34]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>
